function sys = htmpc_example_model()

% Example system from HTMPC paper

sys = struct(...
    'A', [1 1; 0 1], ...
    'B', [0.5;1], ...
    'x0', [-6.5; -2], ...
    'x_min', [-10 -10]', ...
    'x_max', [10 2]', ...
    'u_min', -1, ...
    'u_max', 1, ...
    'w_min', [-0.1 -0.1]', ...
    'w_max', [0.1 0.1]', ...
    'name', 'htmpc_example_model', ...
    'nx', 2, ...
    'nu', 1, ...
    'nw', 2);



